### PR TITLE
Export function to set 'createLogic' options globally

### LINKED ISSUE #51: Question: Can you set warnTimeout globally?
I'd like to set the warnTimeout default much lower for all my logic, is that possible?

### PR DESCRIPTION
**Pull request by sanbornhilland**
Make a single call to the 'configureLogic' function to override the
redux-logic library defaults for the following options:

  warnTimeout
  latest
  debounce
  throttle

Closes #51

### CODE REVIEW

**Comment by jeffbski** [comment]
Thanks @sanbornhilland for the excellent PR including tests. I probably just need to mention its use on the readme and in the API (docs) markdown and then we can merge this in. Feel free to take a stab at that if you want otherwise I can do it.

**Comment by sanbornhilland** [comment]
@jeffbski Yeah I'll take a crack at it. I just wanted you to do a sanity check on it before I invested too much time.

**Comment by sanbornhilland** [comment]
I updated the existing commit to include API documentation. Let me know if you think it's clear enough. It wasn't obvious to me where to include this in the main README but I can update that as well if you have suggestions.

**Comment by jeffbski** [comment]
looks good. I'll work on merging this tomorrow.

**Comment by jeffbski** [comment]
I was just about to merge and then I started thinking thinking about whether we should limit the default options to only things like warnTimeout. Setting the other options needs to be done deliberately case by case.

**Comment by sanbornhilland** [comment]
Do you mean, limiting the default options or limiting the options that are globally configurable? I think it makes sense to always provide sane defaults and it's unclear to me what would happen if there were just no default values at all for `latest`, `throttle`, and `debounce`. If you mean limit which options are globally configurable because it doesn't make sense to set those options globally then I don't have a strong opinion about that. I haven't had a use for those other options in our project so far so I'm less familiar with settings those. If you think it doesn't make sense I'll change it and just make the `warnTimeout` configurable.

**Comment by jeffbski** [comment]
@sanbornhilland Yeah, for the moment I think we should probably just limit the globally configurable items to warnTimeout. For the other ones, it really should be case by case and setting defaults could cause unintended consequences for previously working stacks. 

warnTimeout is a safe option to change (and it is only used in non-production anyway). So I think it makes sense to offer a configuration to either change the default or to disable the feature setting it to 0.

**Comment by sanbornhilland** [comment]
Shoot, broke it. Will fix this later tonight or tomorrow.

**Comment by sanbornhilland** [comment]
@jeffbski Fixed the linting error. Looks like the build is failing now because it's unable to log a coverage report. Missing token?

```
[error] "2018-04-05T16:13:44.708Z"  'Error sending coverage'
[error] "2018-04-05T16:13:44.710Z"  [Error: Token is required]
```

Not sure what's involved here.

**Comment by jeffbski** [comment]
I guess it needs to be updated. I'll check into it. Thanks.

**Comment by jeffbski** [comment]
Deployed as v0.13.0 Thanks @sanbornhilland, wonderful job with the code, test, and docs

**Pull request merged**
