### PR TITLE
Some TypeScript definitions

### PR DESCRIPTION
**Pull request by sykesd**
This is an initial version of a TypeScript typings file - see #8 

This version is enough to get a very simple example to compile. However, the file is incomplete, and the types of some things are still unclear to me. If you are interested in me finishing this up to a point where you could accept it, let me know.

If you are, I will definitely have some questions around what types certain things should have.

### CODE REVIEW

**Comment by jeffbski** [comment]
@sykesd awesome! I'll take a look at what you have started. I definitely would like to get this setup. I just haven't been using TypeScript yet so having someone with experience is a definite plus.

**Comment by sykesd** [comment]
Great. I have left TODO comments in the places where I know the types are incomplete. There are bound to be other cases where the types are incorrect/incomplete that I have missed.
Let me once you have had a chance to take a look.

**Comment by jeffbski** [comment]
Nice work @sykesd, this is shaping up nicely.

**Comment by malafreniere** [comment]
Any ETA on this ? :)

**Comment by sykesd** [comment]
Not at this time. I will put together a list of specific questions I have regarding the parts that are missing and forward them to you as soon as I can.

**Comment by Verbon** [comment]
Any updates about this? Are TypeScript definitions gonna be released sometimes?

**Comment by jeffbski** [comment]
@Verbon I'll see what I can do. I am new to typescript but will see if I can continue the work that @sykesd started.

**Comment by sykesd** [comment]
Really sorry for the radio silence on this. We are using `redux-logic` at work and I got pulled away onto other projects for quite some time. But I am back on a project making use of `redux-logic`.

The types, as present in this merge request still work for us. However, to get to a point where these type definitions can be included in the project itself there are several holes that need to be filled. These are marked with `TODO` in the file itself.

But I will repeat the main ones here.

## Fundamental Questions

1. Should the Redux `Action` type be typed as an [FSA (Flux Standard Action)](https://github.com/redux-utilities/flux-standard-action)?
  We use this quite a bit in our code to add type information, but I realise that not everybody else might.

1. I have a feeling that some of the parameterized types are incorrectly defined. 
  Specifically, I am afraid that I have done some of the "Don'ts" in [this list](http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html).

## More Specific Questions

1. There are several places in `redux-logic` where an [`rxjs`](https://github.com/ReactiveX/RxJS) observable is exposed. I am not familiar with `rxjs` at all, and we don't use it explicitly, so I have not invested the time to learn enough to describe those types.
  Can anybody shed some light on what the type of this observable might be?
  An example of such a case is here:
    ```typescript
    interface LogicHookParams {
      getState: () => any;

      action: LogicAction;

      ctx: object;

      // TODO cancelled$ observable - no idea yet on what its type signature should be
    }
    ```

1. I define a type `ActionTypeMatcher` for the `type` property of a Logic. The docs state that this can be a regular expression, but I am unsure if this is a JavaScript `RegExp` or just a string containing a regular expression?

There are a couple of other questions, but these are probably a good place to start.

**Comment by alvis** [comment]
Sorry to cross the post. I was working on a project with `redux-logic` few months back. At that point this thread was a bit silent so I decided to make my own definition, which is available at https://github.com/alvis/redux-logic/blob/typescript/index.d.ts

It's still WIP, and I also share the same question about FSA as @sykesd. However, it's almost complete as it works fine with my project and it also come with a type test, which includes example usages. There's a few holes from full coverage as I don't use these features, but I'm happy to complete them. Mind me opening another PR for review?

**Comment by jeffbski** [comment]
@alvis Sounds great. I would love to get that added.

**Comment by sykesd** [comment]
@alvis Looks really good! 

@jeffbski I think @alvis PR is more correct that mine, not only because he also has types for the `rxjs` properties, but because of the way he has declared the types from your library itself. I believe it avoids many of the concerns I had about doing it the "wrong" way.

**Comment by jeffbski** [comment]
Thanks for your efforts @sykesd. I have merged @alvis PR and published as 0.15.3

**Pull request closed without merging**
